name: Deploy to Render

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      deployments: write
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production'
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Notify Slack
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Production Deployment Status
          SLACK_MESSAGE: |
            🚀 Deployment to Render ${{ job.status }}
            Branch: `${{ github.ref_name }}`
            Commit: `${{ github.sha }}`
          SLACK_FOOTER: Production Deploy Workflow 