name: Move Trello Cards

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  move-cards:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      TRELLO_DONE_LIST_ID: ${{ secrets.TRELLO_DONE_LIST_ID }}
      TRELLO_REVIEW_LIST_ID: ${{ secrets.TRELLO_REVIEW_LIST_ID }}
    steps:
      - name: Extract Trello Card IDs
        id: extract
        run: |
          CARD_IDS=$(echo "${{ github.event.pull_request.body }}" \
            | grep -oE 'trello\.com/c/[A-Za-z0-9]+' \
            | sed 's#.*/c/##' \
            | uniq \
            | paste -sd',' -)
          echo "Extracted CARD_IDS=$CARD_IDS"
          echo "::set-output name=card_ids::$CARD_IDS"

      - name: Move Cards Based on Target Branch
        if: steps.extract.outputs.card_ids != ''
        run: |
          IFS=',' read -r -a IDS <<< "${{ steps.extract.outputs.card_ids }}"
          case "${{ github.event.pull_request.base.ref }}" in
            main)
              LIST_ID="${{ env.TRELLO_DONE_LIST_ID }}"
              LIST_NAME="Done"
              ;;
            develop)
              LIST_ID="${{ env.TRELLO_REVIEW_LIST_ID }}"
              LIST_NAME="Review"
              ;;
            *)
              echo "Unsupported target branch '${{ github.event.pull_request.base.ref }}'; skipping."
              exit 0
              ;;
          esac
          for CARD_ID in "${IDS[@]}"; do
            echo "Moving card $CARD_ID to $LIST_NAME list"
            curl -s -X PUT "https://api.trello.com/1/cards/$CARD_ID/idList?value=$LIST_ID&key=${{ secrets.TRELLO_KEY }}&token=${{ secrets.TRELLO_TOKEN }}" -o /dev/null
            echo "✅ Moved Trello card $CARD_ID to $LIST_NAME"
          done

      - name: Notify Slack
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Trello Cards Update
          SLACK_MESSAGE: |
            🎯 Trello cards update ${{ job.status }}
            PR: `${{ github.event.pull_request.title }}`
            Branch: `${{ github.event.pull_request.base.ref }}`
            Cards moved to: `${{ job.status == 'success' && 'Done/Review' || 'Failed' }}`
          SLACK_FOOTER: Trello Cards Workflow
