name: Pull Request CI

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened, closed]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest tests/ -v

  notify-test-failure:
    name: Notify Test Failure
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: danger
          SLACK_TITLE: Pull Request Tests Failed
          SLACK_MESSAGE: |
            ❌ Tests failed in Pull Request
            PR: `${{ github.event.pull_request.title }}`
            Author: `${{ github.event.pull_request.user.login }}`
            Please fix the failing tests before merging
          SLACK_FOOTER: Pull Request Workflow

  lint:
    name: Run Linting
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Run black
        run: |
          black . --check

  notify-lint-failure:
    name: Notify Linting Failure
    needs: lint
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: danger
          SLACK_TITLE: Pull Request Linting Failed
          SLACK_MESSAGE: |
            ❌ Linting failed in Pull Request
            PR: `${{ github.event.pull_request.title }}`
            Author: `${{ github.event.pull_request.user.login }}`
            Please fix the linting issues before merging
          SLACK_FOOTER: Pull Request Workflow

  sonarqube:
    name: SonarQube Analysis
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  notify-sonarqube-failure:
    name: Notify SonarQube Failure
    needs: sonarqube
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: danger
          SLACK_TITLE: Pull Request SonarQube Analysis Failed
          SLACK_MESSAGE: |
            ❌ SonarQube analysis failed in Pull Request
            PR: `${{ github.event.pull_request.title }}`
            Author: `${{ github.event.pull_request.user.login }}`
            Please check the SonarQube dashboard for details
          SLACK_FOOTER: Pull Request Workflow

  move-trello-cards:
    name: Move Trello Cards
    needs: [test, lint, sonarqube]
    if: success() && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract Trello Card IDs
        id: extract
        run: |
          # Extract card IDs from PR description using multiple patterns
          CARD_IDS=$(echo "${{ github.event.pull_request.body }}" | grep -o -E 'https://trello.com/c/[A-Za-z0-9]+|trello.com/c/[A-Za-z0-9]+|\[Trello\]\(https://trello.com/c/[A-Za-z0-9]+\)' | sed -E 's/.*trello.com\/c\/([A-Za-z0-9]+).*/\1/')
          if [ -z "$CARD_IDS" ]; then
            echo "No Trello card IDs found in PR description"
            exit 0
          fi
          echo "CARD_IDS=$CARD_IDS" >> $GITHUB_ENV
          
      - name: Move Cards Based on Target Branch
        if: env.CARD_IDS != ''
        run: |
          # Determine target list ID based on the target branch
          if [ "${{ github.base_ref }}" = "main" ]; then
            LIST_ID="${{ secrets.TRELLO_DONE_LIST_ID }}"
            LIST_NAME="Done"
          else
            LIST_ID="${{ secrets.TRELLO_REVIEW_LIST_ID }}"
            LIST_NAME="Review"
          fi
          
          for CARD_ID in ${{ env.CARD_IDS }}; do
            curl -s -X PUT "https://api.trello.com/1/cards/$CARD_ID/idList?value=$LIST_ID&key=${{ secrets.TRELLO_KEY }}&token=${{ secrets.TRELLO_TOKEN }}" -o /dev/null
            echo "✅ Moved Trello card $CARD_ID to $LIST_NAME"
          done

  notify-success:
    name: Notify Success
    needs: [test, lint, sonarqube, move-trello-cards]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: good
          SLACK_TITLE: Pull Request Ready for Review
          SLACK_MESSAGE: |
            ✅ Pull Request passed all checks
            PR: `${{ github.event.pull_request.title }}`
            Author: `${{ github.event.pull_request.user.login }}`
            - Tests: ✅
            - Linting: ✅
            - SonarQube: ✅
            - Trello Cards: ✅
          SLACK_FOOTER: Pull Request Workflow 